### ISSUE TITLE
ERROR: Undefined control sequence. l.117 \git@vtag{\gitInf@refnames}

### ISSUE THREAD

**Issue by 0mid** [Hightor/gitinfo2#1]
I'm trying to use the new gitinfo2 and I have followed the simple setup on page 3 of the manual. (I put the .sty files in my `~/texmf` directory and they are visible to LaTeX as confirmed by running `kpsewhich gitinfo2.sty` and `kpsewhich gitexinfo.sty`. I'm using TeX Live 2012.20120611-3.)
However, when I try to compile the simple TeX file below

``` latex
\documentclass{article}
\usepackage{gitinfo2}

\begin{document}
Hello, World!
\gitAuthorEmail (revision: \gitAbbrevHash, \gitAuthorDate)
\end{document}
```

I get the following error:
ERROR: Undefined control sequence.

--- TeX said ---

``` latex
\do #1->\StrCut 
                {#1}{tag: }\lcut \rcut \IfEq {\rcut }{}{\IfDecimal {\lcut }{...
l.117 \git@vtag{\gitInf@refnames}
```

What am I missing here? The same setup used to work with `gitinfo`.

**Comment by JakeHertenstein** [comment]
Same issue here. Any ideas since your post?

**Comment by longborough** [comment]
Sorry, I can't get this to fail. Could one of you post a log file?

(I'm on TeX Live 2014, completely up-to-date; not complaining, just FYI)

**Comment by longborough** [comment]
Thanks, @JakeHertenstein. This is just for the public record; as per our emails, you are investigating the version of xstring as a first step:

Package: xstring 2010/03/28  v1.5d  String manipulations (C Tellechea) 

Xstring is currently at v1.7c

**Comment by 0mid** [comment]
Brent, per our email, and the comment above, I looked at my version of `xstring` as well. It was older than your version. After upgrading the package (just got the TeX Directory Structure (TDS) form from http://mirror.ctan.org/systems/texlive/tlnet/archive/xstring.tar.xz; extracted it via `tar xJvf` in my `TEXMFHOME` directory, as reported by `kpsewhich -var-value TEXMFHOME`; then checked that it is found by LaTeX, using `kpsewhich xstring.sty`) I can report that the issue is resolved.

**Comment by longborough** [comment]
@0mid Thank you very much. I'll wait to hear from @JakeHertenstein , and then I'll close this issue.

**Comment by JakeHertenstein** [comment]
After the bumpy big switch from MiKTeX to TeX Live on Cygwin, the latest version of xstring appears to be required as I am now able to compile without errors. Thanks for the help!

**Comment by longborough** [comment]
OK, everyone, I'm glad it's solved!
