### ISSUE TITLE
where should gitHeadInfo.gin be?

### ISSUE THREAD

**Issue by maxheld83** [Hightor/gitinfo2#10]
I set up gitinfo2 as advised, with `post-checkout` etc in `myrepo/.git/hooks`.

This creates `gitHeadInfo.gin` in `myrepo`, but both the manual and gitinfo2 seem to expect it elsewhere, as indicated by the below warning:

```
Package gitinfo2 Warning: I can't find the file '.git/gitHeadInfo.gin'.
(gitinfo2)                All git metadata has been set to '(None)'.
```

What did I do wrong?

**Comment by longborough** [comment]
I'm not sure. gitHeadInfo.gin should be in the `.git/` directory. Is it possible that your hook is missing this?:

`... > .git/gitHeadInfo.gin` 

(note the ".git/")

**Comment by longborough** [comment]
Could you post one of your hooks here (assuming they're all the same)? I'm pretty certain this is a problem in the hook.

**Comment by maxheld83** [comment]
sure, thanks for looking into this:

Here's `post-commit`.

```
#!/bin/sh
# Copyright 2011 Brent Longborough
# Please read gitinfo.pdf for licencing and other details
# -----------------------------------------------------
# Post-{commit,checkout,merge} hook for the gitinfo package
#
prefixes=". test docs"    # Example for multiple gitHeadInfo.tex files
prefixes="."              # Default --- in the working copy root
for pref in $prefixes
    do
    git log -1 --date=short \
    --pretty=format:"\usepackage[%
        shash={%h},
        lhash={%H},
        authname={%an},
        authemail={%ae},
        authsdate={%ad},
        authidate={%ai},
        authudate={%at},
        commname={%an},
        commemail={%ae},
        commsdate={%ad},
        commidate={%ai},
        commudate={%at},
        refnames={%d}
    ]{gitsetinfo}" HEAD > $pref/gitHeadInfo.gin
    done
```

**Comment by longborough** [comment]
That explains it. You have the old hooks, from gitinfo version 1. You need to replace them with the sample from gitinfo2, as explained on page 3 of the manual.

Thank you for this issue, as although it was a problem your end, it did also show up a well-hidden bug.

**Comment by maxheld83** [comment]
thanks a bunch and sorry for the needless hassle!

**Comment by longborough** [comment]
My pleasure...  "The Client is always right"
