### ISSUE TITLE
gitinfo2 does not like submodules

### ISSUE THREAD

**Issue by maxheld83** [Hightor/gitinfo2#11]
I have placed (now the correct) `post-checkout` in my (system-wide) `.git-templates`, so that, ideally, whenever I clone or (re-)init a repo, it should be all set up for gitinfo2.

This works fine, _except_ for _submodules_, in which case git shouts something like

```
/Users/Max/Github/emile/.git/modules/emile.wiki/hooks/post-checkout: line 13: .git/gitHeadInfo.gin: Not a directory
Unable to checkout submodule 'emile.wiki'
```

I think the problem is that the hooks for _submodules_ are placed in the `.git` of the _supermodule_, the submodules themselves have no such thing.

**Comment by longborough** [comment]
Hmm. I have three comments, none of which is very helpful -- sorry!
1. I've never used submodules, and have never invested enough time to understand them
2. I've _heard_ (ie may be only gossip) that submodules "don't work very well"; that has compounded the previous item
3. The submodules have, presumably, a separate working copy/repo where they are the "top level thing"; I assume that there, things work OK?
4. The problem itself looks like the hook is getting executed from the wrong "current directory"; you _may_ be able to fix this by adjusting the path to `> .git/gitHeadInfo.gin` in the hooks.

I'm sorry, I just don't know what to do to fix this.

**Comment by longborough** [comment]
For now, I have to close this as a wontfix. I'm sorry, but I just don't have the necessary git knowledge to address this,nor the time to learn just now.
