### ISSUE TITLE
Commands don't print the right metadata

### ISSUE THREAD

**Issue by emalizia** [Hightor/gitinfo2#12]
In version 2.0.4, in order to have the info returned from "git describe" I have to use the command \gitFirstTagDescribe. While \gitDescribe prints only the abbreviated hash.
I don't know whether there are more commands printing the wrong metadata.

**Comment by longborough** [comment]
Could you post a copy of `.git/gitHeadInfo.gin` here? I'm especially interested in the line beginning `reltag={`; the line in your hooks beginning with `RELTAG=$(git describe...` would also be helpful.

It looks like gitinfo2 couldn't find a tag to match whatever your hook is searching for. If you post the information, it shouldn't be too difficult to find out what's happening.

**Comment by emalizia** [comment]
Ok. At the moment I can't send you this information. And I cannot do that for some days. I'll do it as soon as I can.

**Comment by longborough** [comment]
@emalizia OK, just post it whenever you can...

**Comment by emalizia** [comment]
Hello. Sorry for answering after so much time. I couldn't find a way to upload files here.

gitHeadInfo.gin

\usepackage[%
        shash={19e8f32},
        lhash={19e8f326353f42bbc507935f4e77650c63470ca6},
        authname={abc},
        authemail={a@b.c},
        authsdate={2015-02-26},
        authidate={2015-02-26 09:47:39 +0000},
        authudate={1424944059},
        commname={abc},
        commemail={a@b.c},
        commsdate={2015-02-26},
        commidate={2015-02-26 09:47:39 +0000},
        commudate={1424944059},
        refnames={ (HEAD, master)},
        firsttagdescribe={VersionBeginningFeb2015-1-g19e8f32},
        reltag={19e8f32}
    ]{gitexinfo}

post-checkout

#!/bin/sh
#Copyright 2014 Brent Longborough
#Part of gitinfo2 package Version 2
#Please read gitinfo2.pdf for licencing and other details
#-----------------------------------------------------
#Post-{commit,checkout,merge} hook for the gitinfo2 package
#
#Get the first tag found in the history from the current HEAD
FIRSTTAG=$(git describe --tags --always --dirty='-_' 2>/dev/null)
#Get the first tag in history that looks like a Release
RELTAG=$(git describe --tags --long --always --dirty='-_' --match '[0-9]_._' 2>/dev/null)
#Hoover up the metadata
git --no-pager log -1 --date=short --decorate=short \
    --pretty=format:"\usepackage[%
        shash={%h},
        lhash={%H},
        authname={%an},
        authemail={%ae},
        authsdate={%ad},
        authidate={%ai},
        authudate={%at},
        commname={%cn},
        commemail={%ce},
        commsdate={%cd},
        commidate={%ci},
        commudate={%ct},
        refnames={%d},
        firsttagdescribe={$FIRSTTAG},
        reltag={$RELTAG}
    ]{gitexinfo}" HEAD > .git/gitHeadInfo.gin

**Comment by emalizia** [comment]
Sorry I closed this issue by mistake...

**Comment by JakeHertenstein** [comment]
jake.hertenstein@gmail.com has read this message at 1:43 PM on 3/2/2015.

Read receipt sent by Gmelius <http://gmelius.com/?hi>.


Best regards,
Jake Hertenstein

**Comment by longborough** [comment]
I think you need to revisit the match parameter in your hooks. Are you trying to use a regular expression? If so, it won't work; the match parameter has to be a Unix glob expression. Your match is looking for 'a digit followed by a full stop character'. This doesn't match  "VersionBeginningFeb2015", but it would match "VersionBeginningFeb2015.". 

Please let me know whether this explains the problem.

Please leave the issue open; I'll add clarification to the manual when I next release the package.

**Comment by longborough** [comment]
Documentation updated by commit 3b7c095 for release 2.0.5
