### ISSUE TITLE
Undefined control sequence \do #1->\StrCut

### ISSUE THREAD

**Issue by lsandig** [Hightor/gitinfo2#13]
I use gitinfo with the `gitinfo2.sty` and `gitexinfo.sty` copied and checked in to my git repository (no system-wide install).
Compilation on my laptop works (TeX Live 2014/Arch Linux), compilation on another machine (texlive (2012.20120611-5) on debian wheezy) fails with

```
! Undefined control sequence.
\do #1->\StrCut
                {#1}{tag: }\lcut \rcut \IfEq {\rcut }{}{\IfDecimal {\lcut }{...
l.113 \git@vtag{\gitInf@refnames}

?
```

The offending line is the definition of `git@vtag` in `gitexinfo.sty` line 56.

**Comment by longborough** [comment]
Sorry I'm a bit late responding.

gitinfo2 uses the xstring package, which provides `\StrCut` from at least version 1,7c dated 2013-10-13.

My guess is that your TeX Live distribution is hopelessly out-of date, and for that, I'm sorry, but I don't have a fix.

I would strongly recommend that you change your TeX distribution method. The distribution bundled with Linux distributions is often so out-of-date as to be almost useless; I recommend installing the current TeX Live using its own installer (tlmgr), and keeping it up-to-date. There's a small learning investment, but you'll avoid similar irritations in the future.
