### ISSUE TITLE
gitinfo2 cannot handle branches with underscores

### ISSUE THREAD

**Issue by ivokabadshow** [Hightor/gitinfo2#16]
LaTeX will not compile documents using gitinfo2, if the refnames stored in `gitHeadInfo.gin` contain branches with underscores. E.g. `refnames={ (HEAD, master, test_underscore)}`.

LaTeX stops and complains with

```
! Missing $ inserted.
<inserted text> 
$
```

As a quick-fix I detokenized the critical expression in `gitexinfo.sty`, line 81. The original expression to store the branch name `\gitBranch` given as

```
\renewcommand{\gitBranch}{\xcut}%
```

was changed to

```
\renewcommand{\gitBranch}{\detokenize\expandafter{\xcut}}%
```

This solved the problem for me. However the underscore problem might emerge elsewhere again, so one probably has to detokenize more strings.

**Comment by longborough** [comment]
I'm sorry I have not replied sooner. Thank you very much for pointing this out. It's going to need a certain amount of study and work, so I'll leave this open for now.

**Comment by longborough** [comment]
Incorporated into Release 2.0.6 -- Commit 75117b6

This includes Author and Committer Names and emails, plus all git references (branches and tags)
