### ISSUE TITLE
Dirty flag not available for repos without tags

### ISSUE THREAD

**Issue by ivokabadshow** [Hightor/gitinfo2#2]
When using LaTeX+git+gitinfo2, my workflow does usually not include tagging. This however is problematic, since the provided LaTeX hooks in `gitHeadInfo.gin` do not capture the dirty flag if no tag is available.

The `post-{commit,checkout,merge}` files contain the following line:

<pre>
RELTAG=$(git describe --tags --long --dirty='-*' --match '[0-9]*.*' 2>/dev/null)
</pre>

Adding the `--always` keyword helps to obtain the dirty flag also for tag-less repos.

<pre>
RELTAG=$(git describe --tags --long <b>--always</b> --dirty='-*' --match '[0-9]*.*' 2>/dev/null)
</pre>

In my opinion this is much safer, since the dirty flag should not dependent on git tags.

**Comment by longborough** [comment]
Sorry for the delay in answering.
Your solution looks good; I'll test it a bit more, than ship it out, as soon as I can find some time.

**Comment by longborough** [comment]
@ivokabadshow On reflection, I'm thinking of extracting the dirty flag from the other command:

`FIRSTTAG=$(git describe --tags --dirty='-*' 2>/dev/null)`

Can you see any downside to this?

**Comment by ivokabadshow** [comment]
Unless you use the `--always` flag a tag-less repo will not be marked correctly. The `FIRSTTAG` you provided should look like:

<pre>
FIRSTTAG=$(git describe --tags <b>--always</b> --dirty='-*' 2>/dev/null)
</pre>

Without the `--always` flag (and dropping the redirection) `git` complains:

<pre>
fatal: No names found, cannot describe anything.
</pre>

**Comment by longborough** [comment]
Yes, of course; now I understand precisely the problem. Thank you.

**Comment by longborough** [comment]
Fixed in commit e95909a - in release 2.0.4
