### ISSUE TITLE
Even more TeX-hostile characters metadata

### ISSUE THREAD

**Issue by musoke** [Hightor/gitinfo2#24]
The readme mentions the possibility of email addresses which are not so friendly to TeX. However, this doesn't seem to cover the possibility of `%` appearing in the git metadata. I know this may seem obscure, but I actually just ran into a commit whose author made a typo in the email address, resulting in this error:

```
(../.git/gitHeadInfo.gin)
Runaway argument?
shash={1f957a7}, lhash={1f957a772346e23ca42530467210288c67a939bf}, au\ETC.
! File ended while scanning use of \@fileswith@ptions.
<inserted text> 
                \par 
```

I ended up just "fixing" `gitHeadInfo.gin` by hand. I suspect that the simplest solution would be to update the git hooks to sanitise metadata before writing to `gitHeadInfo.gin`.

**Comment by josephwright** [comment]
This repository is no longer active: please re-report issues at https://github.com/josephwright/gitinfo2/issues
