### ISSUE TITLE
Dirty flag not available for dirty repos

### ISSUE THREAD

**Issue by ivokabadshow** [Hightor/gitinfo2#3]
The manual (release2.0 5c264bd) states on page 9 under `gitFirstTagDescribe`:

>  If the working copy is dirty (has uncommitted changes), the string has ’-*’ appended.

Statements about the working copy are a bit misleading, since the working copy can be dirty, but gitinfo2 does not know this. It solely relies on the information in `gitHeadInfo.gin`.
However this information is outdated, if LaTeX files have been edited after the last git activity that updated the hooks. gitinfo2 itself does not (and probably cannot) run any git commands at compile time.

To achieve a workflow that includes the dirty flag as a watermark, the manual should state, that a call to one of the hooks prior to compiling the document is necessary. This avoids having two compiled versions of the LaTeX document with the same watermark (same hash, not reported as dirty) but different content.

**Comment by longborough** [comment]
Absolutely right. Thank you for pointing this out. I'll fix this as soon as I can.

**Comment by ivokabadshow** [comment]
A simplified solution would be a `git checkout` prior to compiling the LaTeX document. The checkout itself (with no additional arguments) is a no-op but runs the post-checkout hook. This procedure updates the dirty flag correctly. In a makefile-based build system this can be easily incorporated.

**Comment by longborough** [comment]
Yes, that's what I do myself.

I really need to add a "Hints and Tips" section to the manual -- when I can find the time :)

**Comment by emalizia** [comment]
Nice trick you guys suggested. I didn't know that 'git checkout' leaves things as they are. Will this behaviour of 'git checkout' without arguments maintained also in the future releases of git?

I use another trick: I checkout a dummy file, i.e., I checkout an empty file before compiling in order to have the dirty flag updated consistently. In order to have the call to git performed automatically before LaTeX compiling I use arara.

**Comment by longborough** [comment]
Another way I do it in some repositories is this: I also keep the output pdf  and other output files (the CTAN archive file, for example) in the repo, although I only check them in very infrequently (eg when I ship a copy). 

You can see a good(?) example in the [Makefile for gitinfo2](https://github.com/Hightor/gitinfo2/blob/develop/Makefile) itself,  

```

```

**Comment by emalizia** [comment]
I see.
Generally I prefer to include the temporary and output files in the .gitignore
Sometimes, instead of checking out a dummy file, I checkout precisely the .gitignore file before running LaTeX.

**Comment by longborough** [comment]
Yes; yours is certainly a valid approach. In my case I need to keep history of the finished pdf, as it goes out to clients and forms the basis for contracts.

**Comment by longborough** [comment]
Just to be tidy, I'm closing this, but please feel at ease to reopen the issue if there are still problems.
