### ISSUE TITLE
Author and Commiter metadata are the same

### ISSUE THREAD

**Issue by emalizia** [Hightor/gitinfo2#5]
In version 2.0.4, when I use commands \gitAuthorIsoDate and \gitCommitterIsoDate I obtain the same values even if the two values should be different, e.g. when a commit is amended.
By looking at the hook file, I think that for the committer metadata the committer placeholders, like for example %cn, should be used.

**Comment by longborough** [comment]
Thank you. I can confirm that's a really careless bug, and I'm very sorry.

I'm out of the UK at the moment and working on a rather demanding (if not exhausting) project, so I hope you'll forgive me if I don't push to CTAN immediately.

**Comment by longborough** [comment]
I've just pushed out the new file, as commit #https://github.com/Hightor/gitinfo2/commit/62f84bdf85150cce9c4929117b3e6ee5a74d87ca

I'll leave the issue open until I get it to CTAN.

**Comment by longborough** [comment]
This will be in release 2.0.5
