### ISSUE TITLE
clarify location of post-xxx-sample.txt in manual

### ISSUE THREAD

**Issue by maxheld83** [Hightor/gitinfo2#6]
this is just a small thing for people like me who are not soo savvy:

I got confused reading the manual as to _where_ I should find the `post-xxx-sample.txt` – maybe a little hint about the location would be helpful.

**Comment by longborough** [comment]
Absolutely right. I'll fix that as soon as I can (not sure when - I'm travelling for most of the rest of the year).

**Comment by longborough** [comment]
Thank you. I'll probably include this as part of a new "Hints and Tips with no Guarantees" chapter I'm dreaming up.

**Comment by longborough** [comment]
I've added this in commit 8ed1932, for release 2.0.5
