### ISSUE TITLE
reference procedure to simplify gitinfo setup for all repos

### ISSUE THREAD

**Issue by maxheld83** [Hightor/gitinfo2#7]
as per: https://coderwall.com/p/jp7d5q
That seems like a good idea...

**Comment by maxheld83** [comment]
Ps.: fantastic work.

**Comment by longborough** [comment]
Maximilian, I'm very sorry it's taken me a year to acknowledge your kind words, for which thank you.

I'm going to close this ticket; although I think this is an excellent suggestion, I need to resist the temptation to turn the manual into a list of helpful `git` tips, as I think I should aim it at those who, like me, approach `git` with a certain amount of fear and trembling. I hope you understand.
