### ISSUE TITLE
require xcolor or sth similar for watermark

### ISSUE THREAD

**Issue by maxheld83** [Hightor/gitinfo2#8]
I'm guessing the `mark` requires `xcolor` or some other other package, because without `\usepackage{xcolor}` I get this:

```
! LaTeX Error: Undefined color `gray'.
```

Problem goes away with xcolor loaded.

Am I right?

Should maybe call that package automatically, or advise users in the manual.

**Comment by longborough** [comment]
Oh, dear. Thanks again for pointing out a defect. I'll fix it as soon as I can.

**Comment by longborough** [comment]
Fixed for release 2.0.5
